// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmdqxyulvtrstkmqujdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttZHF4eXVsdnRyc3RrbXF1amRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNDQwMDMsImV4cCI6MjA1MzgyMDAwM30.fLwzxPtn8vKxv44nxvv27ZCbFO7aoKQozOoh9KNEuKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);